version: "3.9"

services:
  unique:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      # ./postgres to save the volume locally
      - "./postgres:/var/lib/postgresql/data"

volumes:
  postgres:
